// Automatically generated by Interoptopus.

#ifndef rosu_ffi
#define rosu_ffi

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




typedef struct calculateperformanceresult
    {
    double pp;
    double stars;
    } calculateperformanceresult;

///Option type containing boolean flag and maybe valid data.
typedef struct optionu32
    {
    ///Element that is maybe valid.
    uint32_t t;
    ///Byte where `1` means element `t` is valid.
    uint8_t is_some;
    } optionu32;


calculateperformanceresult calculate_score(const int8_t* beatmap_path, uint32_t mode, const int8_t* mods, uint32_t max_combo, double accuracy, uint32_t miss_count, optionu32 passed_objects, bool lazer);

calculateperformanceresult calculate_score_bytes(const uint8_t* beatmap_bytes, uint32_t len, uint32_t mode, uint32_t mods, uint32_t max_combo, double accuracy, uint32_t miss_count, optionu32 passed_objects, bool lazer);


#ifdef __cplusplus
}
#endif

#endif /* rosu_ffi */
